name: kaiteki_lints
version: 0.0.1

environment:
  sdk: '>=3.3.0-2.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
