name: Backend request
description: Request a new backend (e.g. Mastodon) to be added to Kaiteki
title: "Backend request"
labels: [ "enhancement", "backend-request" ]
body:
- type: input
  id: name
  attributes:
    label: Name
  validations:
    required: true
- type: input
  id: link
  attributes:
    label: Link
    description: "A link to the project page, so we can check it out"
    placeholder: "https://example.com/"
  validations:
    required: true
- type: input
  id: api-docs
  attributes:
    label: API Docs Link
    description: "A link to the project's API documentation, without it, we can't support it!"
    placeholder: "https://example.com/api-documentation/"
  validations:
    required: false
- type: textarea
  id: features
  attributes:
    label: Features
    description: "Does the project have features that Kaiteki and/or other projects don't have? What do we need to look out for?"
    placeholder: "- Aside from favoriting your post you can also hug them now"
  validations:
    required: false
