name: fediverse_objects
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.3.3
  http: ^1.0.0
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.17.10