include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**.g.dart'
    - 'lib/l10n/**'
  errors:
    missing_enum_constant_in_switch: ignore
    # Ignoring TODO comments since they're obnoxious
    # to see within the problem list and can be easily
    # viewed with the todo lists within the IDE.
    todo: ignore
    fixme: ignore
    hack: ignore

custom_lint:
  rules:
    # Unreliable, triggers on variables and methods returning expected Widget type.
    - missing_provider_scope: false

linter:
  rules:
    avoid_type_to_string: true
    avoid_positional_boolean_parameters: false

    # Unnecessary code
    avoid_redundant_argument_values: true
    avoid_types_on_closure_parameters: true
    noop_primitive_operations: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    omit_local_variable_types: true

    # Code style
    prefer_double_quotes: true
    always_declare_return_types: true
    avoid_void_async: true
    join_return_with_assignment: true
    only_throw_errors: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    require_trailing_commas: true
    use_named_constants: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_test_throws_matchers: true
    use_super_parameters: true

    # Dart features
    avoid_classes_with_only_static_members: true
    avoid_returning_this: true
    cascade_invocations: true
    prefer_asserts_in_initializer_lists: true
    prefer_if_elements_to_conditional_expressions: true

    # Sorting
    directives_ordering: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true

    # Naming conventions
    flutter_style_todos: true
    use_to_and_as_if_applicable: true
    
    # Flutter
    sized_box_shrink_expand: true
    use_decorated_box: true